### ISSUE TITLE
don't connect to 'pocket.dev' when served from localhost

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-admin-dashboard#19]
on linux we're not using local-tld but just ports on localhost.

We want to connect to `pocket.dev` when developing pocket locally using yeoman. So I'd suggest we also test for the port number, or we make a pocket.local domain that we use for yeoman? @espy

**Comment by janl** [comment]
we are ripping out local-tld support soon, as it is a bit broken.
