### ISSUE TITLE
change heading from "change password" to "change username"

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/hoodie-admin-dashboard#37]
change heading from "change password" to "change username" in the view on changeUsername

**Comment by Charlotteis** [comment]
I can't find any reference to "change password" "change username" or "changeUsername" in either this repository (hoodie-admin-dashboard) or hoodie-admin-dashboard-UIkit. As this is such an old issue it's likely that the dashboard has moved on a lot since it was filed. This should be closed :)

**Comment by gr2m** [comment]
@zoepage can you add more information to this issue? Because I can't find any reference either. And I'd rather tend to close the issue and open a new one, if we run into this again

**Comment by zoepage** [comment]
I've already fixed the issue. Sorry for the confusion.
