### ISSUE TITLE
Cannot find (404) assets (css, images)

### ISSUE THREAD

**Issue by davidpfahler** [hoodiehq/hoodie-admin-dashboard#56]
I `npm install`ed and `bower install`ed. I'm `grunt serve`ing and open http://0.0.0.0:9000/ in Chrome 36. It can't load the required assets.

![screen shot 2014-07-19 at 14 33 28](https://cloud.githubusercontent.com/assets/908242/3634673/fb880690-0f40-11e4-93a4-ce84dd67c6ab.png)

Additionally, `hoodie.js`'s checkConnection function throws this error every second or so:
![screen shot 2014-07-19 at 14 37 56](https://cloud.githubusercontent.com/assets/908242/3634680/8896b478-0f41-11e4-8a7d-b0429f5862aa.png)

**Comment by espy** [comment]
Closed for now, pending rewrite.
