### ISSUE TITLE
[bearer token] Bearer token is not being persisted

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-admin-dashboard#58]
the merge of the bearer token pull requests into hoodie-server / hoodie.js broke the Admin Dashboard :/  Who could pair with me on Wednesday (until 2pm), Thursday or Friday to get this fixed?

@michielbdejong @janl @caolan @boennemann @svnlto 

To reproduce,

- clone hoodie-admin-dashboard,
- `npm install`
- `npm link` the latest hoodie-server https://github.com/hoodiehq/hoodie-server/tree/michiel/fix-tests
- `grunt server` for local dev server

**Comment by michielbdejong** [comment]
I this still an issue?

**Comment by gr2m** [comment]
No, I fixed the issue by using `hoodie.request` which passes the bearer token along. Thanks @michielbdejong
